### PR TITLE
Coins details new info

### PR DESCRIPTION
**Pull request by grdddj**
Fixes https://github.com/trezor/definitions/issues/9
Fixes https://github.com/trezor/definitions/issues/10

New fields and info into `coins_details.json`

### CODE REVIEW

**Comment by matejcik** [comment]
please convert `network` to an object with `key` (current value) and `name` (taken from the parent network)
set `network: null` if it's not a token

explicitly set network={ bitcoin info here } for USDT(OMNI) and MaidSafeCoin (can we tell whether a thing is an Omni chain?)

change `t1_enabled` and `t2_enabled` to `"support": {"T1B1": <bool>, "T2T1": <bool>}`

**Comment by grdddj** [comment]
> please convert `network` to an object with `key` (current value) and `name` (taken from the parent network) set `network: null` if it's not a token

Done in [174715d](https://github.com/trezor/definitions/pull/13/commits/174715dab812ba30c614334b279008b355dfe39e)

> explicitly set network={ bitcoin info here } for USDT(OMNI) and MaidSafeCoin (can we tell whether a thing is an Omni chain?)

Not sure what/how to do this. Can you please give an example result how it should look like?

> change `t1_enabled` and `t2_enabled` to `"support": {"T1B1": <bool>, "T2T1": <bool>, "T2B1": <same value as T2T1 for now>}`

Done in [174715d](https://github.com/trezor/definitions/pull/13/commits/174715dab812ba30c614334b279008b355dfe39e)

**Comment by Hannsek** [comment]
We can adjust it here properly right now. See https://github.com/trezor/trezor-firmware/issues/2793

**Comment by matejcik** [comment]
> We can adjust it here properly right now. See [trezor/trezor-firmware#2793](https://github.com/trezor/trezor-firmware/issues/2793)

i would prefer to first implement that issue in firmware repo and only afterwards start using the resulting data here.

> > explicitly set network={ bitcoin info here } for USDT(OMNI) and MaidSafeCoin (can we tell whether a thing is an Omni chain?)
> 
> Not sure what/how to do this. Can you please give an example result how it should look like?

```
"misc:USDT": {
   ...
   "network": { "key": "bitcoin: BTC", "name": "Bitcoin" }
}
```
dtto for MAID

**Comment by grdddj** [comment]
> > > explicitly set network={ bitcoin info here } for USDT(OMNI) and MaidSafeCoin (can we tell whether a thing is an Omni chain?)
> > 
> > 
> > Not sure what/how to do this. Can you please give an example result how it should look like?
> 
> ```
> "misc:USDT": {
>    ...
>    "network": { "key": "bitcoin:BTC", "name": "Bitcoin" }
> }
> ```
> 
> dtto for MAID

Thanks for the hint, done in [633ddab](https://github.com/trezor/definitions/pull/13/commits/633ddab3c73fe09079b6b3def8d26134e814595a)

**Comment by matejcik** [comment]
ah, there's still the override file, that's nice .)

**Review by matejcik — APPROVED** [review]

**Pull request merged**
